[package]
name = "tunnel-server-tls"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
tunnel-proto = { path = "../tunnel-proto" }
tunnel-router = { path = "../tunnel-router" }
tokio = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true}

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
